/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BorderBox13: typeof import('./components/datav/border-box-13/border-box-13.vue')['default']
    CapsuleChart: typeof import('./components/datav/capsule-chart/capsule-chart.vue')['default']
    CenterBottom: typeof import('./components/echarts-demo/center/center-bottom.vue')['default']
    CenterBottom2: typeof import('./components/echarts-demo/center/center-bottom2.vue')['default']
    CenterBottom3: typeof import('./components/echarts-demo/center/center-bottom3.vue')['default']
    CenterMap: typeof import('./components/echarts-demo/center/center-map.vue')['default']
    CenterOs: typeof import('./components/echarts-demo/center/center-os.vue')['default']
    CountUp: typeof import('./components/count-up/count-up.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    EmptyCom: typeof import('./components/empty-com/empty-com.vue')['default']
    ItemWrap: typeof import('./components/item-wrap/item-wrap.vue')['default']
    LeftBottom: typeof import('./components/echarts-demo/left/left-bottom.vue')['default']
    LeftCenter: typeof import('./components/echarts-demo/left/left-center.vue')['default']
    LeftTop: typeof import('./components/echarts-demo/left/left-top.vue')['default']
    RightBottom: typeof import('./components/echarts-demo/raight/right-bottom.vue')['default']
    RightTop: typeof import('./components/echarts-demo/raight/right-top.vue')['default']
    RightTop2: typeof import('./components/echarts-demo/raight/right-top-2.vue')['default']
    RightTop3: typeof import('./components/echarts-demo/raight/right-top-3.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScaleScreen: typeof import('./components/scale-screen/scale-screen.vue')['default']
    SeamlessScroll: typeof import('./components/seamless-scroll/seamless-scroll.vue')['default']
  }
}
